pipeline {
    agent {
        docker {
            image 'maven:3.9.5-openjdk-17' // Exemplo de uma boa imagem
            args '-u root' // Pode ser necessário dependendo da configuração do seu Jenkins
        }
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
